<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Arch" Version="2.1.0" />
      <PackageReference Include="SDL3-CS" Version="3.4.16" />
      <PackageReference Include="SDL3-CS.Windows" Version="3.4.16" />
      <PackageReference Include="SDL3-CS.Windows.Image" Version="3.4.6.9" />
      <PackageReference Include="SDL3-CS.Windows.Mixer" Version="3.2.4.11" />
      <PackageReference Include="SDL3-CS.Windows.Shadercross" Version="3.0.0.11" />
      <PackageReference Include="SDL3-CS.Windows.TTF" Version="3.2.2.11" />
      <PackageReference Include="VYaml" Version="1.4.0" />
    </ItemGroup>
    
    <ItemGroup>
        <Content Include="Assets/**" CopyToOutputDirectory="Always"  />
    </ItemGroup>
    
    <ItemGroup>
      <ClCompile Include="Assets\builtin\shaders\sprite.hlsl" />
    </ItemGroup>

</Project>
